language: python

python:
  - "3.7"

dist: xenial

before_install:
  - pip install poetry

install:
  - poetry install -v

script:
  - pytest

notifications:
  email: false

cache:
  directories:
    - "node_modules"